# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guillya5.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import QApplication

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1214, 878)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 1191, 711))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_3 = QtWidgets.QLabel(self.page_3)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 471, 21))
        self.label_3.setObjectName("label_3")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.page_3)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 70, 1081, 321))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(5)
        self.tableWidget_3.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 2, item)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(210)
        self.tableWidget_3.verticalHeader().setDefaultSectionSize(70)
        self.tableWidget_3.verticalHeader().setMinimumSectionSize(25)
        self.label_4 = QtWidgets.QLabel(self.page_3)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 471, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.page_3)
        self.label_5.setGeometry(QtCore.QRect(10, 390, 471, 21))
        self.label_5.setObjectName("label_5")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.page_3)
        self.tableWidget_4.setGeometry(QtCore.QRect(10, 410, 821, 211))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(1)
        self.tableWidget_4.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(5, 0, item)
        self.tableWidget_4.horizontalHeader().setDefaultSectionSize(800)
        self.stackedWidget.addWidget(self.page_3)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(0, 10, 471, 21))
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.page)
        self.tableWidget.setGeometry(QtCore.QRect(0, 40, 1081, 151))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.page)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 230, 1031, 431))
        self.tableWidget_2.setLineWidth(1)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(14)
        self.tableWidget_2.setRowCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(6, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(7, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(8, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(8, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(8, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(8, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(9, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(9, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(9, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(9, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(9, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(10, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(10, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(10, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(10, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(10, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(10, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(10, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(10, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(10, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(10, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(12, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(12, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(12, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(12, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(12, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(12, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(12, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(12, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(12, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(12, 12, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(70)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(38)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(30)
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(0, 200, 471, 21))
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(0, 10, 471, 21))
        self.label_2.setObjectName("label_2")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget_5.setGeometry(QtCore.QRect(0, 30, 651, 551))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(6)
        self.tableWidget_5.setRowCount(17)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(5, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(6, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(7, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(8, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(9, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(9, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(10, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(10, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(10, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(11, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(11, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(11, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(12, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(12, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(12, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(13, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(13, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(13, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(14, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(14, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(14, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(14, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(15, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(15, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(15, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(15, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(16, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(16, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(16, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(16, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(16, 5, item)
        self.pushButton = QtWidgets.QPushButton(self.page_2)
        self.pushButton.setGeometry(QtCore.QRect(680, 30, 451, 31))
        self.pushButton.setObjectName("pushButton")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget_6.setGeometry(QtCore.QRect(680, 80, 431, 571))
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(2)
        self.tableWidget_6.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setItem(5, 0, item)
        self.tableWidget_6.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget_6.verticalHeader().setDefaultSectionSize(90)
        self.stackedWidget.addWidget(self.page_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1000, 750, 161, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 750, 171, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 750, 161, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        #MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1214, 29))
        self.menubar.setObjectName("menubar")
        #MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Дані про задачу:</span></p></body></html>"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Приорітети держави"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Орг.-розробники"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Джерела інвестицій"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Орієнтація продукту"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Конкуренція"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        item = self.tableWidget_3.item(0, 0)
        item.setText(_translate("MainWindow", "1.1 Продукція подвійного призначення"))
        item = self.tableWidget_3.item(0, 1)
        item.setText(_translate("MainWindow", "2.1. Державні розробники"))
        item = self.tableWidget_3.item(0, 2)
        item.setText(_translate("MainWindow", "3.1. Відсутні"))
        item = self.tableWidget_3.item(0, 3)
        item.setText(_translate("MainWindow", "4.1. Внутрішнє вмкористання"))
        item = self.tableWidget_3.item(0, 4)
        item.setText(_translate("MainWindow", "5.1. Висока"))
        item = self.tableWidget_3.item(1, 0)
        item.setText(_translate("MainWindow", "1.2. Нові прилади, електроніка"))
        item = self.tableWidget_3.item(1, 1)
        item.setText(_translate("MainWindow", "2.2. Приватні компанії"))
        item = self.tableWidget_3.item(1, 2)
        item.setText(_translate("MainWindow", "3.2. Державні"))
        item = self.tableWidget_3.item(1, 3)
        item.setText(_translate("MainWindow", "4.2. Експорт"))
        item = self.tableWidget_3.item(1, 4)
        item.setText(_translate("MainWindow", "5.2. Середня"))
        item = self.tableWidget_3.item(2, 0)
        item.setText(_translate("MainWindow", "1.3. Програмне забезпечення"))
        item = self.tableWidget_3.item(2, 1)
        item.setText(_translate("MainWindow", "2.3. Науково-дослідні інститути"))
        item = self.tableWidget_3.item(2, 2)
        item.setText(_translate("MainWindow", "3.3. Приватні"))
        item = self.tableWidget_3.item(2, 4)
        item.setText(_translate("MainWindow", "5.3. Низька"))
        item = self.tableWidget_3.item(3, 0)
        item.setText(_translate("MainWindow", "1.4 Технології зв\"язку"))
        item = self.tableWidget_3.item(3, 1)
        item.setText(_translate("MainWindow", "2.4. Університети"))
        item = self.tableWidget_3.item(3, 2)
        item.setText(_translate("MainWindow", "3.4. Іноземні"))
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Морфологічна таблиця ситуації ІКТ:</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Альтернативи напрямків діяльності:</span></p></body></html>"))
        item = self.tableWidget_4.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_4.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_4.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_4.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_4.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_4.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "А. Напрямки діяльності"))
        __sortingEnabled = self.tableWidget_4.isSortingEnabled()
        self.tableWidget_4.setSortingEnabled(False)
        item = self.tableWidget_4.item(0, 0)
        item.setText(_translate("MainWindow", "А.1. Розробка обладнання для впровадження технологій 4G"))
        item = self.tableWidget_4.item(1, 0)
        item.setText(_translate("MainWindow", "А.2. Розробка удосконалених безпілотних літальних апаратів"))
        item = self.tableWidget_4.item(2, 0)
        item.setText(_translate("MainWindow", "А.3. Розробка сучасного універсального робота зі штучним інтелектом"))
        item = self.tableWidget_4.item(3, 0)
        item.setText(_translate("MainWindow", "А.4. Розробка високоточних вимірювальних приладів"))
        item = self.tableWidget_4.item(4, 0)
        item.setText(_translate("MainWindow", "А.5. Розробка програмного забезпечення для електростанцій"))
        item = self.tableWidget_4.item(5, 0)
        item.setText(_translate("MainWindow", "А.6. Розробка сучасних програм навчання"))
        self.tableWidget_4.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Експертні оцінки морфологічної таблиці:</span></p></body></html>"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Альт 1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Альт 2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Альт 3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Альт 4"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Приор."))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Оргран."))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Інвест."))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Орієнт."))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Конкур."))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "0,65"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "0,2"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "0,05"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "0,8"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "0,35"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "0,8"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "0,35"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("MainWindow", "0,35"))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("MainWindow", "0,65"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "0,2"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "0,65"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("MainWindow", "0,65"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("MainWindow", "-"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "2.1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2.2"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2.3"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "2.4"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "3.1"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "3.2"))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "3.3"))
        item = self.tableWidget_2.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "3.4"))
        item = self.tableWidget_2.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "4.1"))
        item = self.tableWidget_2.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "4.2"))
        item = self.tableWidget_2.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "5.1"))
        item = self.tableWidget_2.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "5.2"))
        item = self.tableWidget_2.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "5.3"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1.1"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "1.2"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "1.3"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "1.4"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "2.1"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "2.2"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "2.3"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "2.4"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "3.1"))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "3.2"))
        item = self.tableWidget_2.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "3.3"))
        item = self.tableWidget_2.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "3.4"))
        item = self.tableWidget_2.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "4.1"))
        item = self.tableWidget_2.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "4.2"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget_2.item(0, 1)
        item.setText(_translate("MainWindow", "0,2"))
        item = self.tableWidget_2.item(0, 3)
        item.setText(_translate("MainWindow", "0,2"))
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("MainWindow", "-0,6"))
        item = self.tableWidget_2.item(2, 0)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget_2.item(2, 1)
        item.setText(_translate("MainWindow", "0,2"))
        item = self.tableWidget_2.item(2, 3)
        item.setText(_translate("MainWindow", "0,2"))
        item = self.tableWidget_2.item(3, 0)
        item.setText(_translate("MainWindow", "0,3"))
        item = self.tableWidget_2.item(4, 4)
        item.setText(_translate("MainWindow", "-0,5"))
        item = self.tableWidget_2.item(4, 5)
        item.setText(_translate("MainWindow", "-0,7"))
        item = self.tableWidget_2.item(4, 6)
        item.setText(_translate("MainWindow", "-0,3"))
        item = self.tableWidget_2.item(4, 7)
        item.setText(_translate("MainWindow", "-0,1"))
        item = self.tableWidget_2.item(5, 0)
        item.setText(_translate("MainWindow", "0,7"))
        item = self.tableWidget_2.item(5, 3)
        item.setText(_translate("MainWindow", "0,2"))
        item = self.tableWidget_2.item(5, 4)
        item.setText(_translate("MainWindow", "0,6"))
        item = self.tableWidget_2.item(5, 6)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget_2.item(5, 7)
        item.setText(_translate("MainWindow", "0,3"))
        item = self.tableWidget_2.item(6, 1)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget_2.item(6, 2)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget_2.item(6, 3)
        item.setText(_translate("MainWindow", "0,2"))
        item = self.tableWidget_2.item(6, 5)
        item.setText(_translate("MainWindow", "0,7"))
        item = self.tableWidget_2.item(7, 1)
        item.setText(_translate("MainWindow", "0,3"))
        item = self.tableWidget_2.item(7, 2)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget_2.item(7, 5)
        item.setText(_translate("MainWindow", "0,7"))
        item = self.tableWidget_2.item(8, 0)
        item.setText(_translate("MainWindow", "0,7"))
        item = self.tableWidget_2.item(8, 1)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget_2.item(8, 2)
        item.setText(_translate("MainWindow", "0,3"))
        item = self.tableWidget_2.item(8, 3)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget_2.item(8, 4)
        item.setText(_translate("MainWindow", "0,4"))
        item = self.tableWidget_2.item(8, 6)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget_2.item(8, 7)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget_2.item(8, 8)
        item.setText(_translate("MainWindow", "-0,1"))
        item = self.tableWidget_2.item(8, 9)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget_2.item(9, 0)
        item.setText(_translate("MainWindow", "-0,3"))
        item = self.tableWidget_2.item(9, 1)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget_2.item(9, 2)
        item.setText(_translate("MainWindow", "0,1"))
        item = self.tableWidget_2.item(9, 3)
        item.setText(_translate("MainWindow", "0,3"))
        item = self.tableWidget_2.item(9, 4)
        item.setText(_translate("MainWindow", "0,4"))
        item = self.tableWidget_2.item(9, 5)
        item.setText(_translate("MainWindow", "0,6"))
        item = self.tableWidget_2.item(9, 8)
        item.setText(_translate("MainWindow", "-0,3"))
        item = self.tableWidget_2.item(9, 10)
        item.setText(_translate("MainWindow", "0,4"))
        item = self.tableWidget_2.item(9, 11)
        item.setText(_translate("MainWindow", "0,7"))
        item = self.tableWidget_2.item(10, 1)
        item.setText(_translate("MainWindow", "0,3"))
        item = self.tableWidget_2.item(10, 2)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget_2.item(10, 3)
        item.setText(_translate("MainWindow", "0,3"))
        item = self.tableWidget_2.item(10, 4)
        item.setText(_translate("MainWindow", "-0,2"))
        item = self.tableWidget_2.item(10, 5)
        item.setText(_translate("MainWindow", "0,7"))
        item = self.tableWidget_2.item(10, 6)
        item.setText(_translate("MainWindow", "-0,3"))
        item = self.tableWidget_2.item(10, 7)
        item.setText(_translate("MainWindow", "-0,4"))
        item = self.tableWidget_2.item(10, 8)
        item.setText(_translate("MainWindow", "-0,8"))
        item = self.tableWidget_2.item(10, 9)
        item.setText(_translate("MainWindow", "-0,4"))
        item = self.tableWidget_2.item(10, 10)
        item.setText(_translate("MainWindow", "0,3"))
        item = self.tableWidget_2.item(10, 11)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget_2.item(10, 13)
        item.setText(_translate("MainWindow", "0,3"))
        item = self.tableWidget_2.item(12, 1)
        item.setText(_translate("MainWindow", "-0,2"))
        item = self.tableWidget_2.item(12, 2)
        item.setText(_translate("MainWindow", "-0,5"))
        item = self.tableWidget_2.item(12, 3)
        item.setText(_translate("MainWindow", "-0,3"))
        item = self.tableWidget_2.item(12, 4)
        item.setText(_translate("MainWindow", "0,2"))
        item = self.tableWidget_2.item(12, 5)
        item.setText(_translate("MainWindow", "-0,7"))
        item = self.tableWidget_2.item(12, 6)
        item.setText(_translate("MainWindow", "0,3"))
        item = self.tableWidget_2.item(12, 7)
        item.setText(_translate("MainWindow", "0,4"))
        item = self.tableWidget_2.item(12, 8)
        item.setText(_translate("MainWindow", "0,8"))
        item = self.tableWidget_2.item(12, 9)
        item.setText(_translate("MainWindow", "0,4"))
        item = self.tableWidget_2.item(12, 10)
        item.setText(_translate("MainWindow", "-0,3"))
        item = self.tableWidget_2.item(12, 11)
        item.setText(_translate("MainWindow", "-0,5"))
        item = self.tableWidget_2.item(12, 12)
        item.setText(_translate("MainWindow", "0,3"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Матриця взаємозв\'язків:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Матриця зв\'язків із альтернативами:</span></p></body></html>"))
        item = self.tableWidget_5.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1.1"))
        item = self.tableWidget_5.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1.2"))
        item = self.tableWidget_5.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "1.3"))
        item = self.tableWidget_5.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "1.4"))
        item = self.tableWidget_5.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "2.1"))
        item = self.tableWidget_5.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "2.2"))
        item = self.tableWidget_5.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "2.3"))
        item = self.tableWidget_5.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "2.4"))
        item = self.tableWidget_5.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "3.1"))
        item = self.tableWidget_5.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "3.2"))
        item = self.tableWidget_5.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "3.3"))
        item = self.tableWidget_5.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "3.4"))
        item = self.tableWidget_5.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "4.1"))
        item = self.tableWidget_5.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "4.2"))
        item = self.tableWidget_5.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "5.1"))
        item = self.tableWidget_5.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "5.2"))
        item = self.tableWidget_5.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "5.3"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "А.1"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "А.2"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "А.3"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "А.4"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "А.5"))
        item = self.tableWidget_5.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "А.6"))
        __sortingEnabled = self.tableWidget_5.isSortingEnabled()
        self.tableWidget_5.setSortingEnabled(False)
        item = self.tableWidget_5.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_5.item(0, 1)
        item.setText(_translate("MainWindow", "0,8"))
        item = self.tableWidget_5.item(0, 2)
        item.setText(_translate("MainWindow", "0,2"))
        item = self.tableWidget_5.item(0, 3)
        item.setText(_translate("MainWindow", "0,4"))
        item = self.tableWidget_5.item(0, 4)
        item.setText(_translate("MainWindow", "0,1"))
        item = self.tableWidget_5.item(0, 5)
        item.setText(_translate("MainWindow", "0,1"))
        item = self.tableWidget_5.item(1, 0)
        item.setText(_translate("MainWindow", "0,3"))
        item = self.tableWidget_5.item(1, 1)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget_5.item(1, 2)
        item.setText(_translate("MainWindow", "0,7"))
        item = self.tableWidget_5.item(1, 3)
        item.setText(_translate("MainWindow", "0,9"))
        item = self.tableWidget_5.item(1, 4)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_5.item(1, 5)
        item.setText(_translate("MainWindow", "0,1"))
        item = self.tableWidget_5.item(2, 0)
        item.setText(_translate("MainWindow", "0,2"))
        item = self.tableWidget_5.item(2, 1)
        item.setText(_translate("MainWindow", "0,1"))
        item = self.tableWidget_5.item(2, 2)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget_5.item(2, 3)
        item.setText(_translate("MainWindow", "-0,2"))
        item = self.tableWidget_5.item(2, 4)
        item.setText(_translate("MainWindow", "0,8"))
        item = self.tableWidget_5.item(2, 5)
        item.setText(_translate("MainWindow", "0,6"))
        item = self.tableWidget_5.item(3, 0)
        item.setText(_translate("MainWindow", "0,9"))
        item = self.tableWidget_5.item(3, 1)
        item.setText(_translate("MainWindow", "0,1"))
        item = self.tableWidget_5.item(3, 2)
        item.setText(_translate("MainWindow", "0,1"))
        item = self.tableWidget_5.item(3, 3)
        item.setText(_translate("MainWindow", "-0,2"))
        item = self.tableWidget_5.item(3, 4)
        item.setText(_translate("MainWindow", "0,3"))
        item = self.tableWidget_5.item(3, 5)
        item.setText(_translate("MainWindow", "0,1"))
        item = self.tableWidget_5.item(4, 0)
        item.setText(_translate("MainWindow", "0,1"))
        item = self.tableWidget_5.item(4, 1)
        item.setText(_translate("MainWindow", "0,3"))
        item = self.tableWidget_5.item(4, 2)
        item.setText(_translate("MainWindow", "0,6"))
        item = self.tableWidget_5.item(4, 3)
        item.setText(_translate("MainWindow", "0,7"))
        item = self.tableWidget_5.item(4, 4)
        item.setText(_translate("MainWindow", "0,8"))
        item = self.tableWidget_5.item(4, 5)
        item.setText(_translate("MainWindow", "0,3"))
        item = self.tableWidget_5.item(5, 0)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget_5.item(5, 1)
        item.setText(_translate("MainWindow", "0,6"))
        item = self.tableWidget_5.item(5, 2)
        item.setText(_translate("MainWindow", "0,4"))
        item = self.tableWidget_5.item(5, 3)
        item.setText(_translate("MainWindow", "0,2"))
        item = self.tableWidget_5.item(5, 4)
        item.setText(_translate("MainWindow", "-0,3"))
        item = self.tableWidget_5.item(5, 5)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget_5.item(6, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_5.item(6, 1)
        item.setText(_translate("MainWindow", "0,4"))
        item = self.tableWidget_5.item(6, 2)
        item.setText(_translate("MainWindow", "0,8"))
        item = self.tableWidget_5.item(6, 3)
        item.setText(_translate("MainWindow", "0,8"))
        item = self.tableWidget_5.item(6, 4)
        item.setText(_translate("MainWindow", "0,6"))
        item = self.tableWidget_5.item(6, 5)
        item.setText(_translate("MainWindow", "0,8"))
        item = self.tableWidget_5.item(7, 0)
        item.setText(_translate("MainWindow", "0,2"))
        item = self.tableWidget_5.item(7, 1)
        item.setText(_translate("MainWindow", "0,7"))
        item = self.tableWidget_5.item(7, 2)
        item.setText(_translate("MainWindow", "0,4"))
        item = self.tableWidget_5.item(7, 3)
        item.setText(_translate("MainWindow", "0,3"))
        item = self.tableWidget_5.item(7, 4)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_5.item(7, 5)
        item.setText(_translate("MainWindow", "0,7"))
        item = self.tableWidget_5.item(8, 0)
        item.setText(_translate("MainWindow", "-0,8"))
        item = self.tableWidget_5.item(8, 1)
        item.setText(_translate("MainWindow", "-0,2"))
        item = self.tableWidget_5.item(8, 2)
        item.setText(_translate("MainWindow", "-0,8"))
        item = self.tableWidget_5.item(8, 3)
        item.setText(_translate("MainWindow", "-0,3"))
        item = self.tableWidget_5.item(8, 4)
        item.setText(_translate("MainWindow", "-0,2"))
        item = self.tableWidget_5.item(8, 5)
        item.setText(_translate("MainWindow", "-0,4"))
        item = self.tableWidget_5.item(9, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_5.item(9, 1)
        item.setText(_translate("MainWindow", "0,1"))
        item = self.tableWidget_5.item(9, 2)
        item.setText(_translate("MainWindow", "-0,1"))
        item = self.tableWidget_5.item(9, 3)
        item.setText(_translate("MainWindow", "0,3"))
        item = self.tableWidget_5.item(9, 4)
        item.setText(_translate("MainWindow", "0,3"))
        item = self.tableWidget_5.item(9, 5)
        item.setText(_translate("MainWindow", "0,2"))
        item = self.tableWidget_5.item(10, 0)
        item.setText(_translate("MainWindow", "0,3"))
        item = self.tableWidget_5.item(10, 1)
        item.setText(_translate("MainWindow", "0,4"))
        item = self.tableWidget_5.item(10, 2)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget_5.item(10, 3)
        item.setText(_translate("MainWindow", "0,3"))
        item = self.tableWidget_5.item(10, 4)
        item.setText(_translate("MainWindow", "-0,4"))
        item = self.tableWidget_5.item(10, 5)
        item.setText(_translate("MainWindow", "0,4"))
        item = self.tableWidget_5.item(11, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_5.item(11, 1)
        item.setText(_translate("MainWindow", "0,7"))
        item = self.tableWidget_5.item(11, 2)
        item.setText(_translate("MainWindow", "0,6"))
        item = self.tableWidget_5.item(11, 3)
        item.setText(_translate("MainWindow", "0,4"))
        item = self.tableWidget_5.item(11, 4)
        item.setText(_translate("MainWindow", "-0,2"))
        item = self.tableWidget_5.item(11, 5)
        item.setText(_translate("MainWindow", "0,2"))
        item = self.tableWidget_5.item(12, 0)
        item.setText(_translate("MainWindow", "0,6"))
        item = self.tableWidget_5.item(12, 1)
        item.setText(_translate("MainWindow", "0,7"))
        item = self.tableWidget_5.item(12, 2)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget_5.item(12, 3)
        item.setText(_translate("MainWindow", "0,6"))
        item = self.tableWidget_5.item(12, 4)
        item.setText(_translate("MainWindow", "0,8"))
        item = self.tableWidget_5.item(12, 5)
        item.setText(_translate("MainWindow", "0,7"))
        item = self.tableWidget_5.item(13, 0)
        item.setText(_translate("MainWindow", "0,2"))
        item = self.tableWidget_5.item(13, 1)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget_5.item(13, 2)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget_5.item(13, 3)
        item.setText(_translate("MainWindow", "0,7"))
        item = self.tableWidget_5.item(13, 4)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_5.item(13, 5)
        item.setText(_translate("MainWindow", "0,3"))
        item = self.tableWidget_5.item(14, 0)
        item.setText(_translate("MainWindow", "-0,3"))
        item = self.tableWidget_5.item(14, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_5.item(14, 2)
        item.setText(_translate("MainWindow", "-0,2"))
        item = self.tableWidget_5.item(14, 3)
        item.setText(_translate("MainWindow", "-0,1"))
        item = self.tableWidget_5.item(14, 4)
        item.setText(_translate("MainWindow", "-0,7"))
        item = self.tableWidget_5.item(14, 5)
        item.setText(_translate("MainWindow", "-0,7"))
        item = self.tableWidget_5.item(15, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_5.item(15, 1)
        item.setText(_translate("MainWindow", "0,2"))
        item = self.tableWidget_5.item(15, 2)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_5.item(15, 3)
        item.setText(_translate("MainWindow", "0,1"))
        item = self.tableWidget_5.item(15, 4)
        item.setText(_translate("MainWindow", "-0,2"))
        item = self.tableWidget_5.item(15, 5)
        item.setText(_translate("MainWindow", "0,1"))
        item = self.tableWidget_5.item(16, 0)
        item.setText(_translate("MainWindow", "0,4"))
        item = self.tableWidget_5.item(16, 1)
        item.setText(_translate("MainWindow", "0,3"))
        item = self.tableWidget_5.item(16, 2)
        item.setText(_translate("MainWindow", "0,4"))
        item = self.tableWidget_5.item(16, 3)
        item.setText(_translate("MainWindow", "0,3"))
        item = self.tableWidget_5.item(16, 4)
        item.setText(_translate("MainWindow", "0,5"))
        item = self.tableWidget_5.item(16, 5)
        item.setText(_translate("MainWindow", "0,5"))
        self.tableWidget_5.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "Порахувати результативонсті"))
        item = self.tableWidget_6.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_6.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_6.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_6.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_6.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_6.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Альтернатива"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Результативність"))
        __sortingEnabled = self.tableWidget_6.isSortingEnabled()
        self.tableWidget_6.setSortingEnabled(False)
        item = self.tableWidget_6.item(0, 0)
        item.setText(_translate("MainWindow", "А.1. Розробка обладнання для впровадження 3G"))
        item = self.tableWidget_6.item(1, 0)
        item.setText(_translate("MainWindow", "А.2. Розробка удосконалених безпілотних літальних апаратів"))
        item = self.tableWidget_6.item(2, 0)
        item.setText(_translate("MainWindow", "А.3. Розробка сучасного універсального робота зі штучним ітнелектом"))
        item = self.tableWidget_6.item(3, 0)
        item.setText(_translate("MainWindow", "А.4. Розробка високоточних вимірювальних приладів"))
        item = self.tableWidget_6.item(4, 0)
        item.setText(_translate("MainWindow", "А.5. Розробка програмного забезпечення для електростанцій"))
        item = self.tableWidget_6.item(5, 0)
        item.setText(_translate("MainWindow", "А.6. Розробка сучасних програм навчання"))
        self.tableWidget_6.setSortingEnabled(__sortingEnabled)
        self.pushButton_4.setText(_translate("MainWindow", "Обрахування"))
        self.pushButton_3.setText(_translate("MainWindow", "Дані задачі"))
        self.pushButton_2.setText(_translate("MainWindow", "Умови задачі"))

'''

class ControlMainWindow(QtGui.QMainWindow):
    def __init__(self, parent=None):
        super(ControlMainWindow, self).__init__(parent)
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        self.ui.pushButton_2.clicked.connect(lambda : self.ui.stackedWidget.setCurrentIndex(0))
        self.ui.pushButton_3.clicked.connect(lambda : self.ui.stackedWidget.setCurrentIndex(1))
        self.ui.pushButton_4.clicked.connect(lambda : self.ui.stackedWidget.setCurrentIndex(2))
        #self.ui.wgtMainWindow.clicked.connect(lambda : self.ui.stackedWidget.setCurrentIndex(1))


'''
if __name__ == '__main__':

    import sys
    app = QApplication(sys.argv)
    window = Window()
    window.show()
    sys.exit(app.exec_())


